// src/App.tsx
function App() {
  const font = { fontFamily: 'Lucida Sans Unicode, Lucida Grande, sans-serif' };
  const mainColor = { color: '#fff' };
  const largeFont = { fontSize: 24 };
  const smallFont = { fontSize: 14 };
  const heading = {
    ...font,
    ...largeFont,
    fontWeight: 'bold'
  };
  const subHeading = {
    ...heading,
    ...mainColor,
    ...smallFont
  };
  const hyperlink = {
    ...font,
    ...mainColor,
    ...smallFont,
    textDecoration: 'none !important'
  };

  return (
    <table cellPadding="0" cellSpacing="0" width="100%" bgcolor="#fff">
      <tr>
        <td height="15"></td>
      </tr>
      <tr>
        <td>
          <table cellPadding="0" cellSpacing="0" width="100%" bgcolor="#303030">
            <tr>
              <td height="15" colSpan={3}></td>
            </tr>
            <tr>
              <td width="15"></td>
              <td style={heading}>
                <span style={{ color: '#b5d443' }}>Omar Mirza</span>
              </td>
              <td width="15"></td>
            </tr>
            <tr>
              <td height="5" colSpan={3}></td>
            </tr>
            <tr>
              <td width="15"></td>
              <td style={subHeading}>Senior Front End Developer | Contract</td>
              <td width="15"></td>
            </tr>
            <tr>
              <td height="25" colSpan={3}></td>
            </tr>
            <tr>
              <td width="15"></td>
              <td style={hyperlink}>
                <a style={hyperlink} href="tel:07932 566 488">
                  07932 566 488
                </a>
                &nbsp;&nbsp;
                <a
                  style={hyperlink}
                  href="https://www.linkedin.com/in/omarcreativedev"
                  target="_blank"
                  rel="noreferrer"
                >
                  LinkedIn
                </a>
              </td>
              <td width="15"></td>
            </tr>
            <tr>
              <td height="15" colSpan={3}></td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  );
}

export default App;

// src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'email-signature';
}

<!--[if mso]>
  <style type="text/css">
    body,
    table,
    td {
      font-family: 'Lucida Sans Unicode', 'Lucida Grande', sans-serif !important;
    }
  </style>
<![endif]-->

<table cellpadding="0" cellspacing="0" width="100%" bgcolor="#fff">
  <tr>
    <td height="15"></td>
  </tr>
  <tr>
    <td>
      <table cellpadding="0" cellspacing="0" width="100%" bgcolor="#303030">
        <tr>
          <td height="15" colspan="3"></td>
        </tr>
        <tr>
          <td width="15"></td>
          <td
            style="font-family: 'Lucida Sans Unicode', 'Lucida Grande', sans-serif;
						font-size: 24px;
						font-weight: bold"
          >
            <span style="color: #b5d443">Omar Mirza</span>
          </td>
          <td width="15"></td>
        </tr>
        <tr>
          <td width="15"></td>
          <td
            style="font-family: 'Lucida Sans Unicode', 'Lucida Grande', sans-serif;
						font-size: 14px;
						font-weight: bold"
          >
            <span style="color: #fff">Contract Front End Developer</span>
          </td>
          <td width="15"></td>
        </tr>
        <tr>
          <td height="30" colspan="3"></td>
        </tr>
        <tr>
          <td width="15"></td>
          <td
            style="color:#fff;
						font-family: 'Lucida Sans Unicode', 'Lucida Grande', sans-serif;
						font-size: 14px;
						font-weight: bold"
          >
            <a
              style="color:#b5d443;
							text-decoration: none !important;
							font-family: 'Lucida Sans Unicode', 'Lucida Grande', sans-serif;
							font-size: 14px;
							font-weight: bold"
              href="https://github.com/omarCreativeDev/cv/raw/master/Omar-Mirza-Contract-Front-End-Developer.pdf"
              target="_blank"
            >
              <span style="color:#b5d443; text-decoration: none !important">
                Get my CV
              </span>
            </a>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <a
              style="color:#fff;
							text-decoration: none !important;
							font-family: 'Lucida Sans Unicode', 'Lucida Grande', sans-serif;
							font-size: 14px"
              href="tel:07932 566 488"
            >
              <span style="color:#fff; text-decoration: none !important">
                07932 566 488
              </span>
            </a>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <a
              style="color:#fff;
							text-decoration: none !important;
							font-family: 'Lucida Sans Unicode', 'Lucida Grande', sans-serif;
							font-size: 14px"
              href="https://www.linkedin.com/in/omarcreativedev"
              target="_blank"
            >
              <span style="color:#fff; text-decoration: none !important">
                LinkedIn
              </span>
            </a>
          </td>
          <td width="15"></td>
        </tr>
        <tr>
          <td height="15" colspan="3"></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
